server:
  port: 8082

spring:
  application:
    name: microsservice-email
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: "amqps://fkmqvjdt:TCfpj63dxTsNMiVrZctEkrXqSnJiD4fl@possum.lmq.cloudamqp.com/fkmqvjdt"
  mail:
    host: smtp.gmail.com
    port: 587
    username: testesoftware***@gmail.com
    password: ********
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

broker:
  queue:
    email:
      name: default.email
